#!/bin/zsh

# Clone the rofi repo
git clone https://github.com/DaveDavenport/rofi

# Update all submodules and initalize them
git submodule update --init

# run autoreconf and install them
autoreconf -i

# Make the build directory
mkdir build
cd build

# Configure the build
../configure

make

# Install rofi!
make install # Can use root if needed.

# Clean up
rm -rf rofi